apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: bluecompute
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    tier: backend
    micro: orders
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: bluecompute
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    tier: backend
    micro: orders
