apiVersion: v1
description: BlueCompute Orders Microservice
name: orders
version: 0.1.2
home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
sources:
  - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-orders/tree/microprofile
