{{ if or .Values.global.istio.enabled .Values.istio.enabled }}
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: {{ template "orders.fullname" . }}
spec:
  targets:
  - name: {{ template "orders.fullname" . }}
    ports:
    - number: {{ .Values.service.externalPort }}
  peers:
  {{- if eq .Values.istio.mTLS "ISTIO_MUTUAL" }}
  - mtls: {}
  {{- end }}
{{ end }}
