---        
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  labels:
    app: bluecompute
    tier: backend
    micro: orders
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: bluecompute
    tier: backend
    micro: orders
...
