apiVersion: v1
entries:
  orders:
  - apiVersion: v1
    created: "2019-11-20T14:27:06.011286-06:00"
    description: BlueCompute Orders Microservice
    digest: cc955922386b1f2a6c71205ccd4d3a4c54c4b6013b14da3c48e964e47da13758
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: orders
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-orders/tree/microprofile
    urls:
    - orders-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v1
    created: "2019-11-20T14:27:06.009752-06:00"
    description: BlueCompute Orders Microservice
    digest: a0b96197e3637ba98cd46e1accd81e098fbd00c2e2c487581456465bdf75e36e
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: orders
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-orders/tree/microprofile
    urls:
    - orders-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    created: "2019-11-20T14:27:06.007637-06:00"
    description: BlueCompute Orders Microservice
    digest: c25abc811ea536f251ad8606aca2e1ebf95bd1d38d50e7a215daa2b99d6e79b7
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: orders
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-orders/tree/microprofile
    urls:
    - orders-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    created: "2019-11-20T14:27:06.005882-06:00"
    description: BlueCompute Orders Microservice
    digest: abac7c97d6b7818c17d14ece7b1f7fbd5ebba175de2422325a6d3aecd823f7ee
    home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
    name: orders
    sources:
    - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-orders/tree/microprofile
    urls:
    - orders-0.0.1.tgz
    version: 0.0.1
generated: "2019-11-20T14:27:06.004964-06:00"
