apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: bluecompute
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    tier: backend
    micro: {{ .Values.micro }}

spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        tier: backend
        micro: {{ .Values.micro }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: {{ .Chart.Name }}-mysql
            - mountPath: /var/run/secrets/binding-refarch-compose-for-mysql
              name: {{ .Chart.Name }}-secret
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.dbname | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mysqluser | quote }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key:  mysqlpass
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "false"
          livenessProbe:
            exec:
              command:
              - mysqladmin
              - ping
            initialDelaySeconds: 45
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - mysqladmin
              - ping
            initialDelaySeconds: 15
            timeoutSeconds: 2
      volumes:
        - name: {{ .Chart.Name }}-mysql
          hostPath:
            path: /var/lib/mysql
        - name: {{ .Chart.Name }}-secret
          secret:
            defaultMode: 420
            secretName: "{{ .Chart.Name }}-secret"
