apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    app: bluecompute
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    tier: backend
    micro: {{ .Values.micro }}
type: Opaque
data:
  mysqluser: {{ .Values.mysqluser | b64enc | quote }}
  mysqlpass: {{ randAlphaNum 10 | b64enc | quote }}
