apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    app: bluecompute
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    tier: backend
    micro: {{ .Values.micro }}
type: Opaque
data:
  {{- $mypass := randAlphaNum 10 }}
  {{- $svchost := (cat .Chart.Name `-service` | nospace) }}
  mysqluser: {{ .Values.mysqluser | b64enc | quote }}
  mysqlpass: {{ $mypass | b64enc | quote }}
  binding: {{ cat `{"uri": "mysql://` .Values.mysqluser `:` $mypass `@` $svchost `:3306/` .Values.dbname `" }` | nospace | b64enc }
